# Servidor
server.port=${PORT:8080}

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-billowing-snow-acft9bms-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_I10WPnoLKmCh
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
